packages:
  - packages/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  'eslint-plugin-react-hooks>zod-validation-error': '4.0.2'
