packages:
  - packages/*

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - fumadocs-mdx@15.0.9
  - miniflare@4.20260526.0
  - shadcn@4.8.1
  - wrangler@4.95.0
  - baseline-browser-mapping@2.11.23
  - fumadocs-core@16.15.10
  - fumadocs-ui@16.15.10
  - zod@4.6.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  'eslint-plugin-react-hooks>zod-validation-error': '4.0.2'
